import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowDown, ArrowLeft, ArrowUp, Download, Eye, FilePenLine, ImagePlus, Loader2, Plus, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { checkUserRole } from "@/lib/supabase-helpers";
import { defaultSectionContent, mergeSiteSettings, siteDefaults, type ContentCard, type SiteSettings } from "@/lib/site-content";
import { compressImage } from "@/lib/image-compressor";

type Section = { id: string; title: string; subtitle: string | null; section_type: string; content: any; order_index: number; is_active: boolean };
const asText = (value: unknown) => typeof value === "string" ? value : "";
const asList = (value: unknown): any[] => Array.isArray(value) ? value : [];
const jsonText = (value: unknown) => JSON.stringify(value, null, 2);

const SiteEditor = () => {
  const navigate = useNavigate(); const { toast } = useToast();
  const [settings, setSettings] = useState<SiteSettings>(siteDefaults); const [sections, setSections] = useState<Section[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [editorOpen, setEditorOpen] = useState(false); const [editing, setEditing] = useState<Partial<Section> | null>(null); const [contentText, setContentText] = useState("{}");
  const orderedSections = useMemo(() => [...sections].sort((a, b) => a.order_index - b.order_index), [sections]);
  useEffect(() => { void (async () => {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session || await checkUserRole(session.user.id) !== "admin") { navigate("/admin/login"); return; }
    const [{ data: settingsRows }, { data: sectionRows }] = await Promise.all([supabase.from("site_settings").select("key, value"), supabase.from("site_sections").select("*").order("order_index")]);
    setSettings(mergeSiteSettings(settingsRows)); setSections(sectionRows || []); setLoading(false);
  })(); }, [navigate]);
  const update = <K extends keyof SiteSettings>(key: K, value: SiteSettings[K]) => setSettings((previous) => ({ ...previous, [key]: value }));
  const saveSettings = async (keys: (keyof SiteSettings)[]) => { setSaving(true); const payload = keys.map((key) => ({ key, value: settings[key] })); const { error } = await supabase.from("site_settings").upsert(payload, { onConflict: "key" }); setSaving(false); if (error) toast({ title: "Could not save", description: error.message, variant: "destructive" }); else toast({ title: "Site content saved", description: "Your public landing page will use these changes." }); };
  const openSection = (section?: Section) => { const next = section || { title: "", subtitle: "", section_type: "announcement", content: defaultSectionContent.announcement, is_active: true }; setEditing(next); setContentText(jsonText(next.content)); setEditorOpen(true); };
  const saveSection = async () => { if (!editing?.title?.trim()) { toast({ title: "A section title is required", variant: "destructive" }); return; } let content: any; try { content = JSON.parse(contentText); } catch { toast({ title: "Content must be valid JSON", description: "Correct the JSON before saving.", variant: "destructive" }); return; } const payload = { title: editing.title.trim(), subtitle: editing.subtitle?.trim() || null, section_type: editing.section_type || "announcement", content, is_active: editing.is_active ?? true, order_index: editing.id ? editing.order_index : (orderedSections.at(-1)?.order_index ?? -1) + 1 }; const response = editing.id ? await supabase.from("site_sections").update(payload).eq("id", editing.id).select().single() : await supabase.from("site_sections").insert(payload).select().single(); if (response.error) { toast({ title: "Could not save section", description: response.error.message, variant: "destructive" }); return; } setSections((previous) => editing.id ? previous.map((section) => section.id === editing.id ? response.data : section) : [...previous, response.data]); setEditorOpen(false); toast({ title: "Section saved" }); };
  const move = async (section: Section, direction: -1 | 1) => { const index = orderedSections.findIndex((item) => item.id === section.id); const neighbour = orderedSections[index + direction]; if (!neighbour) return; const first = await supabase.from("site_sections").update({ order_index: neighbour.order_index }).eq("id", section.id); const second = first.error ? null : await supabase.from("site_sections").update({ order_index: section.order_index }).eq("id", neighbour.id); if (first.error || second?.error) { toast({ title: "Could not reorder", variant: "destructive" }); return; } setSections((current) => current.map((item) => item.id === section.id ? { ...item, order_index: neighbour.order_index } : item.id === neighbour.id ? { ...item, order_index: section.order_index } : item)); };
  const toggle = async (section: Section) => { const { error } = await supabase.from("site_sections").update({ is_active: !section.is_active }).eq("id", section.id); if (!error) setSections((current) => current.map((item) => item.id === section.id ? { ...item, is_active: !item.is_active } : item)); };
  const remove = async (section: Section) => { if (!window.confirm(`Delete “${section.title}”? This cannot be undone.`)) return; const { error } = await supabase.from("site_sections").delete().eq("id", section.id); if (error) toast({ title: "Could not delete", variant: "destructive" }); else setSections((current) => current.filter((item) => item.id !== section.id)); };
  if (loading) return <div className="flex min-h-screen items-center justify-center text-muted-foreground">Loading site editor…</div>;
  const hero = settings.hero_content; const info = settings.admission_info_content; const features = settings.features_content; const contact = settings.contact_settings; const footer = settings.footer_content;
  return <div className="min-h-screen bg-secondary"><header className="bg-primary px-4 py-4 text-primary-foreground"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><div className="flex items-center gap-3"><Button variant="ghost" size="sm" className="hover:bg-white/10" onClick={() => navigate("/admin/dashboard")}><ArrowLeft className="mr-1 h-4 w-4" /> Back</Button><h1 className="font-bold">Site content editor</h1></div><Button variant="secondary" size="sm" onClick={() => window.open("/", "_blank")}><Eye className="mr-2 h-4 w-4" /> Preview</Button></div></header><main className="mx-auto max-w-6xl p-4 md:p-6"><Tabs defaultValue="hero" className="space-y-5"><TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="hero">Hero & identity</TabsTrigger><TabsTrigger value="information">Admission info</TabsTrigger><TabsTrigger value="features">Why choose us</TabsTrigger><TabsTrigger value="contact">Contact & footer</TabsTrigger><TabsTrigger value="sections">Page sections</TabsTrigger><TabsTrigger value="form">Form settings</TabsTrigger></TabsList>
    <TabsContent value="hero"><EditorCard title="Hero & school identity" save={() => saveSettings(["hero_content", "footer_content"])} saving={saving}><Field label="School name" value={asText(footer.school_name)} onChange={(value) => update("footer_content", { ...footer, school_name: value })} /><Field label="Admission badge" value={asText(hero.badge_text)} onChange={(value) => update("hero_content", { ...hero, badge_text: value })} /><Field label="Hero heading" value={asText(hero.title)} onChange={(value) => update("hero_content", { ...hero, title: value })} /><TextField label="Hero sub-heading" value={asText(hero.subtitle)} onChange={(value) => update("hero_content", { ...hero, subtitle: value })} /><TextField label="School address" value={asText(hero.address)} onChange={(value) => update("hero_content", { ...hero, address: value })} /><Field label="Primary button label" value={asText(hero.primary_btn_text)} onChange={(value) => update("hero_content", { ...hero, primary_btn_text: value })} /><Field label="Secondary button label" value={asText(hero.secondary_btn_text)} onChange={(value) => update("hero_content", { ...hero, secondary_btn_text: value })} /><TextField label="Four journey steps (one per line)" value={asList(hero.journey_steps).join("\n")} onChange={(value) => update("hero_content", { ...hero, journey_steps: value.split("\n").map((item) => item.trim()).filter(Boolean) })} /></EditorCard></TabsContent>
    <TabsContent value="information"><EditorCard title="Admission information cards" save={() => saveSettings(["admission_info_content", "quick_tracker_settings"])} saving={saving}><Field label="Section eyebrow" value={asText(info.eyebrow)} onChange={(value) => update("admission_info_content", { ...info, eyebrow: value })} /><Field label="Section heading" value={asText(info.title)} onChange={(value) => update("admission_info_content", { ...info, title: value })} /><TextField label="Section sub-heading" value={asText(info.subtitle)} onChange={(value) => update("admission_info_content", { ...info, subtitle: value })} /><ContentCardsEditor cards={asList(info.cards) as ContentCard[]} onChange={(cards) => update("admission_info_content", { ...info, cards })} includeItems /><div className="rounded-lg border p-4"><div className="flex items-center justify-between"><Label>Show quick tracker</Label><Switch checked={Boolean(settings.quick_tracker_settings.is_enabled)} onCheckedChange={(value) => update("quick_tracker_settings", { ...settings.quick_tracker_settings, is_enabled: value })} /></div><Field label="Tracker input placeholder" value={asText(settings.quick_tracker_settings.search_placeholder)} onChange={(value) => update("quick_tracker_settings", { ...settings.quick_tracker_settings, search_placeholder: value })} /><TextField label="Tracker helper text" value={asText(settings.quick_tracker_settings.helper_text)} onChange={(value) => update("quick_tracker_settings", { ...settings.quick_tracker_settings, helper_text: value })} /></div></EditorCard></TabsContent>
    <TabsContent value="features"><EditorCard title="Why families choose ADIS" save={() => saveSettings(["features_content"])} saving={saving}><Field label="Eyebrow" value={asText(features.eyebrow)} onChange={(value) => update("features_content", { ...features, eyebrow: value })} /><Field label="Heading" value={asText(features.title)} onChange={(value) => update("features_content", { ...features, title: value })} /><ContentCardsEditor cards={asList(features.cards) as ContentCard[]} onChange={(cards) => update("features_content", { ...features, cards })} /></EditorCard></TabsContent>
    <TabsContent value="contact"><EditorCard title="Contact, WhatsApp & footer" save={() => saveSettings(["contact_settings", "footer_content"])} saving={saving}><TextField label="Helpline phone numbers (one per line)" value={asList(contact.phone_numbers).join("\n")} onChange={(value) => update("contact_settings", { ...contact, phone_numbers: value.split("\n").map((number) => number.trim()).filter(Boolean) })} /><Field label="WhatsApp number with country code" value={asText(contact.whatsapp_number)} onChange={(value) => update("contact_settings", { ...contact, whatsapp_number: value.replace(/[^\d+]/g, "") })} /><TextField label="WhatsApp greeting message" value={asText(contact.whatsapp_message)} onChange={(value) => update("contact_settings", { ...contact, whatsapp_message: value })} /><div className="flex items-center justify-between rounded-lg border p-4"><div><Label>Enable floating WhatsApp button</Label><p className="text-sm text-muted-foreground">When off, WhatsApp appears in the help section and footer instead.</p></div><Switch checked={Boolean(contact.is_floating_whatsapp)} onCheckedChange={(value) => update("contact_settings", { ...contact, is_floating_whatsapp: value })} /></div><Field label="Help section title" value={asText(contact.helpline_title)} onChange={(value) => update("contact_settings", { ...contact, helpline_title: value })} /><TextField label="Help section subtitle" value={asText(contact.helpline_subtitle)} onChange={(value) => update("contact_settings", { ...contact, helpline_subtitle: value })} /><TextField label="Footer address" value={asText(footer.address)} onChange={(value) => update("footer_content", { ...footer, address: value })} /><Field label="Footer copyright" value={asText(footer.copyright_text)} onChange={(value) => update("footer_content", { ...footer, copyright_text: value })} /></EditorCard></TabsContent>
    <TabsContent value="sections"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Modular landing-page sections</CardTitle><p className="mt-1 text-sm text-muted-foreground">Add announcements, age criteria, FAQs, facilities, or custom information cards.</p></div><Button onClick={() => openSection()}><Plus className="mr-2 h-4 w-4" /> Add section</Button></CardHeader><CardContent className="space-y-3">{orderedSections.length === 0 && <p className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">No custom sections yet.</p>}{orderedSections.map((section, index) => <div className="flex flex-col gap-3 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between" key={section.id}><div><p className="font-semibold">{section.title}</p><p className="text-sm capitalize text-muted-foreground">{section.section_type.replace("_", " ")} · {section.is_active ? "Visible" : "Hidden"}</p></div><div className="flex flex-wrap items-center gap-2"><Button size="icon" variant="outline" disabled={index === 0} onClick={() => move(section, -1)}><ArrowUp className="h-4 w-4" /></Button><Button size="icon" variant="outline" disabled={index === orderedSections.length - 1} onClick={() => move(section, 1)}><ArrowDown className="h-4 w-4" /></Button><Switch checked={section.is_active} onCheckedChange={() => toggle(section)} /><Button size="sm" variant="outline" onClick={() => openSection(section)}><FilePenLine className="mr-1 h-4 w-4" /> Edit</Button><Button size="icon" variant="ghost" className="text-destructive" onClick={() => remove(section)}><Trash2 className="h-4 w-4" /></Button></div></div>)}</CardContent></Card></TabsContent>
    <TabsContent value="form"><Card><CardHeader><CardTitle>Admission form settings</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Form fields, admission-card instructions, and signatures continue to be managed in the form settings screen.</p><Button className="mt-4" onClick={() => navigate("/admin/settings")}>Open form settings</Button></CardContent></Card></TabsContent>
  </Tabs></main><Dialog open={editorOpen} onOpenChange={setEditorOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editing?.id ? "Edit section" : "Add section"}</DialogTitle></DialogHeader><div className="space-y-4"><Field label="Section title" value={editing?.title || ""} onChange={(value) => setEditing((current) => ({ ...current, title: value }))} /><TextField label="Optional subtitle" value={editing?.subtitle || ""} onChange={(value) => setEditing((current) => ({ ...current, subtitle: value }))} /><div className="space-y-2"><Label>Section type</Label><Select value={editing?.section_type} onValueChange={(value) => { setEditing((current) => ({ ...current, section_type: value })); if (!editing?.id) setContentText(jsonText(defaultSectionContent[value] || {})); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="announcement">Announcement</SelectItem><SelectItem value="age_criteria">Age criteria</SelectItem><SelectItem value="school_features">School features / facilities</SelectItem><SelectItem value="custom_cards">Custom info cards</SelectItem><SelectItem value="faq">FAQ</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Section content (JSON)</Label><Textarea className="min-h-64 font-mono text-xs" value={contentText} onChange={(event) => setContentText(event.target.value)} /><p className="text-xs text-muted-foreground">Use the provided template. This keeps each section extensible while preserving structured content.</p></div></div><DialogFooter><Button variant="outline" onClick={() => setEditorOpen(false)}>Cancel</Button><Button onClick={saveSection}>Save section</Button></DialogFooter></DialogContent></Dialog></div>;
};
const EditorCard = ({ title, children, save, saving }: { title: string; children: React.ReactNode; save: () => void; saving: boolean }) => <Card><CardHeader className="flex-row items-center justify-between"><CardTitle>{title}</CardTitle><Button onClick={save} disabled={saving}><Save className="mr-2 h-4 w-4" /> {saving ? "Saving…" : "Save changes"}</Button></CardHeader><CardContent className="space-y-4">{children}</CardContent></Card>;
const Field = ({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) => <div className="space-y-2"><Label>{label}</Label><Input value={value} onChange={(event) => onChange(event.target.value)} /></div>;
const TextField = ({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) => <div className="space-y-2"><Label>{label}</Label><Textarea value={value} onChange={(event) => onChange(event.target.value)} /></div>;

const ContentCardsEditor = ({ cards, onChange, includeItems = false }: { cards: ContentCard[]; onChange: (cards: ContentCard[]) => void; includeItems?: boolean }) => {
  const { toast } = useToast(); const [uploadingId, setUploadingId] = useState<string | null>(null);
  const replace = (id: string, patch: Partial<ContentCard>) => onChange(cards.map((card) => card.id === id ? { ...card, ...patch } : card));
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= cards.length) return; const next = [...cards]; [next[index], next[target]] = [next[target], next[index]]; onChange(next); };
  const upload = async (card: ContentCard, file: File) => {
    try {
      setUploadingId(card.id);
      const isImage = file.type.startsWith("image/");
      const prepared = isImage ? await compressImage(file, { maxSizeBytes: 1024 * 1024, maxWidthOrHeight: 1600 }) : file;
      const extension = prepared.name.split(".").pop() || (isImage ? "jpg" : "pdf");
      const path = `cards/${card.id}-${Date.now()}.${extension}`;
      const { error } = await supabase.storage.from("site-assets").upload(path, prepared, { upsert: false, contentType: prepared.type });
      if (error) throw error;
      const { data } = supabase.storage.from("site-assets").getPublicUrl(path);
      replace(card.id, isImage ? { image_url: data.publicUrl } : { document_url: data.publicUrl, document_label: card.document_label || "Download file" });
      toast({ title: "Asset uploaded", description: "Save page changes to publish this card." });
    } catch (error) { toast({ title: "Upload failed", description: error instanceof Error ? error.message : "Please try again.", variant: "destructive" }); }
    finally { setUploadingId(null); }
  };
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Content cards</h3><p className="text-sm text-muted-foreground">Add, reorder, or enrich cards with a public image or download.</p></div><Button type="button" size="sm" onClick={() => onChange([...cards, { id: crypto.randomUUID(), title: "New card", description: "", items: [] }])}><Plus className="mr-1 h-4 w-4" /> Add New Card</Button></div>{cards.map((card, index) => <div className="rounded-lg border p-4" key={card.id}><div className="mb-3 flex items-center justify-between"><p className="font-medium">Card {index + 1}</p><div className="flex gap-1"><Button type="button" size="icon" variant="outline" disabled={index === 0} onClick={() => move(index, -1)}><ArrowUp className="h-4 w-4" /></Button><Button type="button" size="icon" variant="outline" disabled={index === cards.length - 1} onClick={() => move(index, 1)}><ArrowDown className="h-4 w-4" /></Button><Button type="button" size="icon" variant="ghost" className="text-destructive" onClick={() => { if (window.confirm(`Delete “${card.title}”?`)) onChange(cards.filter((item) => item.id !== card.id)); }}><Trash2 className="h-4 w-4" /></Button></div></div><div className="grid gap-3 md:grid-cols-2"><Field label="Title" value={card.title} onChange={(value) => replace(card.id, { title: value })} /><TextField label="Description" value={card.description || ""} onChange={(value) => replace(card.id, { description: value })} /></div>{includeItems && <TextField label="Bullet points (one per line)" value={(card.items || []).join("\n")} onChange={(value) => replace(card.id, { items: value.split("\n").map((item) => item.trim()).filter(Boolean) })} />}<Field label="Download label" value={card.document_label || ""} onChange={(value) => replace(card.id, { document_label: value })} /><div className="mt-3 flex flex-wrap items-center gap-3">{card.image_url && <img className="h-16 w-24 rounded border object-cover" src={card.image_url} alt="Card preview" />}{card.document_url && <a className="inline-flex items-center gap-1 text-sm text-primary underline" href={card.document_url} target="_blank" rel="noreferrer"><Download className="h-4 w-4" /> Current file</a>}<Label className="inline-flex min-h-9 cursor-pointer items-center gap-2 rounded-md border bg-background px-3 py-2 text-sm hover:bg-muted"><ImagePlus className="h-4 w-4" /> {uploadingId === card.id ? <><Loader2 className="h-4 w-4 animate-spin" /> Optimizing image...</> : "Upload image or PDF"}<Input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/*,application/pdf" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(card, file); event.target.value = ""; }} /></Label></div></div>)}</div>;
};
export default SiteEditor;
