import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ClipboardList, FileText, LogOut, Printer, Search, Eye, ArrowRight, CheckCircle2, Circle, Clock3 } from "lucide-react";

const StudentDashboard = () => {
  const [applications, setApplications] = useState<any[]>([]); const [tests, setTests] = useState<any[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true);
  const [searchParams, setSearchParams] = useSearchParams(); const [activeTab, setActiveTab] = useState(searchParams.get("tab") || "admissions"); const navigate = useNavigate();
  useEffect(() => { const init = async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) return navigate("/student/login"); const [apps, admissionTests] = await Promise.all([supabase.from("applications").select("*").eq("user_id", session.user.id).order("created_at", { ascending: false }), supabase.from("admission_tests").select("*").eq("user_id", session.user.id).order("created_at", { ascending: false })]); setApplications(apps.data || []); setTests(admissionTests.data || []); setLoading(false); }; init(); const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => { if (!session) navigate("/student/login"); }); return () => subscription.unsubscribe(); }, [navigate]);
  const changeTab = (tab: string) => { setActiveTab(tab); setSearchParams({ tab }); };
  const logout = async () => { await supabase.auth.signOut(); navigate("/"); };
  const matches = (item: any, id: string, name: string) => !search || item[id]?.toLowerCase().includes(search.toLowerCase()) || item[name]?.toLowerCase().includes(search.toLowerCase());
  const filteredApps = applications.filter(a => matches(a, "application_id", "full_name")); const filteredTests = tests.filter(t => matches(t, "test_id", "student_name"));
  return <div className="min-h-screen bg-[#f7faf8]"><header className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><img src="/lovable-uploads/b3369ca5-553a-4c65-961b-27d4deb3ca86.jpg" alt="School logo" className="h-10 w-10 rounded-full border border-white/30" /><div><h1 className="font-bold">My admission dashboard</h1><p className="text-xs text-white/70">Alor Disha Islamic School</p></div></div><Button variant="ghost" size="sm" className="text-white hover:bg-white/10 hover:text-white" onClick={logout}><LogOut className="mr-1 h-4 w-4" /> Sign out</Button></div></header>
    <main className="mx-auto max-w-6xl space-y-6 px-4 py-6 sm:px-6"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-black/5"><p className="text-sm font-semibold text-primary">Welcome back</p><div className="mt-2 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold">Keep your admission on track.</h2><p className="mt-1 text-sm text-muted-foreground">Apply, view your status, and download documents from one place.</p></div><div className="flex gap-2"><Button onClick={() => navigate("/student/new-admission")}><FileText className="mr-2 h-4 w-4" /> New application</Button><Button variant="outline" onClick={() => navigate("/student/admission-test")}><ClipboardList className="mr-2 h-4 w-4" /> Admission test</Button></div></div></section>
      <div className="grid gap-4 sm:grid-cols-3"><Stat label="Applications" value={applications.length} /><Stat label="Under review" value={applications.filter(a => a.status === "Pending").length} tone="amber" /><Stat label="Approved" value={applications.filter(a => a.status === "Approved").length} tone="green" /></div>
      <section className="rounded-xl bg-white p-4 shadow-sm ring-1 ring-black/5"><div className="relative mb-4 max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search by name or ID" value={search} onChange={e => setSearch(e.target.value)} /></div><Tabs value={activeTab} onValueChange={changeTab}><TabsList className="grid w-full grid-cols-2 sm:w-auto"><TabsTrigger value="admissions">Applications ({applications.length})</TabsTrigger><TabsTrigger value="tests">Tests ({tests.length})</TabsTrigger></TabsList><TabsContent value="admissions" className="mt-4 space-y-3">{loading ? <Empty text="Loading your applications…" /> : filteredApps.length ? filteredApps.map(app => <ApplicationCard key={app.id} app={app} onView={() => window.open(`/print/admission/${app.id}?view=true`, "_blank")} onPrint={() => navigate(`/print/admission/${app.id}`)} />) : <Empty text="No applications yet. Start a new application when you are ready." />}</TabsContent><TabsContent value="tests" className="mt-4 space-y-3">{loading ? <Empty text="Loading your test applications…" /> : filteredTests.length ? filteredTests.map(test => <TestCard key={test.id} test={test} onView={() => window.open(`/print/test/${test.id}?view=true`, "_blank")} onPrint={() => navigate(`/print/admit-card/${test.id}`)} />) : <Empty text="No admission test applications yet." />}</TabsContent></Tabs></section></main></div>;
};
const Stat = ({ label, value, tone = "primary" }: { label: string; value: number; tone?: "primary" | "amber" | "green" }) => <Card><CardContent className="p-4"><p className="text-sm text-muted-foreground">{label}</p><p className={`mt-1 text-3xl font-bold ${tone === "amber" ? "text-amber-600" : tone === "green" ? "text-green-600" : "text-primary"}`}>{value}</p></CardContent></Card>;
const statusClass = (status: string) => status === "Approved" ? "bg-green-100 text-green-800" : status === "Rejected" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800";
const Timeline = ({ status }: { status: string }) => { const steps = ["Submitted", "Under review", status === "Rejected" ? "Decision" : "Approved"]; const current = status === "Approved" || status === "Rejected" ? 2 : 1; return <div className="mt-5 grid grid-cols-3 gap-1">{steps.map((step, index) => <div key={step} className="flex items-center gap-1 text-[11px] text-muted-foreground"><span className={index <= current ? "text-primary" : "text-muted-foreground/50"}>{index < current ? <CheckCircle2 className="h-4 w-4" /> : <Circle className="h-4 w-4" />}</span><span>{step}</span></div>)}</div>; };
const ApplicationCard = ({ app, onView, onPrint }: { app: any; onView: () => void; onPrint: () => void }) => <Card><CardContent className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{app.full_name}</h3><Badge className={statusClass(app.status)} variant="secondary">{app.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{app.application_id} · Applying for {app.desired_class} · {app.session || "Session not set"}</p><Timeline status={app.status} /></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={onView}><Eye className="mr-1 h-4 w-4" /> View</Button><Button size="sm" variant="outline" onClick={onPrint}><Printer className="mr-1 h-4 w-4" /> Print</Button></div></div></CardContent></Card>;
const TestCard = ({ test, onView, onPrint }: { test: any; onView: () => void; onPrint: () => void }) => <Card><CardContent className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{test.student_name}</h3><Badge className={statusClass(test.status)} variant="secondary">{test.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{test.test_id} · {test.applying_for_class} · {test.session}</p>{test.status === "Approved" ? <p className="mt-3 flex items-center gap-2 text-sm font-medium text-green-700"><CheckCircle2 className="h-4 w-4" /> Admit card is available{test.roll_no ? ` · Roll no. ${test.roll_no}` : ""}</p> : <p className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><Clock3 className="h-4 w-4" /> Your test application is being reviewed.</p>}</div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={onView}><Eye className="mr-1 h-4 w-4" /> View</Button>{test.status === "Approved" && <Button size="sm" onClick={onPrint}><Printer className="mr-1 h-4 w-4" /> Admit card</Button>}</div></div></CardContent></Card>;
const Empty = ({ text }: { text: string }) => <div className="rounded-lg border border-dashed p-10 text-center text-sm text-muted-foreground">{text}<ArrowRight className="ml-1 inline h-4 w-4" /></div>;
export default StudentDashboard;
