// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olqvnhufcionpbekhvvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9scXZuaHVmY2lvbnBiZWtodnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5Njg2MDgsImV4cCI6MjEwNTU0NDYwOH0.tCdLO1wyFq75qdvUjVKY2bvk1yzYsyZ_QYNM7j-kp6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});